version: "3"

services:
  governance-ga-web:
    image: ${ECR_REGISTRY}/governance-ga-web:${IMAGE_TAG:-latest}
    container_name: governance-ga-web
    build:
      context: .
      dockerfile: ./dockerfiles/fastapi/Dockerfile
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - ./shared_models/shared_models.py:/app/shared_models.py
      - ./app:/app
      - ./environments/governance-ga/fastapi.default.env:/app/.env
    depends_on:
      - governance-ga-wallets-db
      - ledger-nodes
      - ledger-browser
    networks:
      - governance-ga
      - host
    env_file:
      - environments/governance-ga/fastapi.default.env
  governance-ga-wallets-db:
    #image: ${ECR_REGISTRY}/postgres:11
    container_name: governance-ga-wallets-db
    image: postgres:11
    command: postgres -c listen_addresses='*'
    env_file:
      - environments/governance-ga/db.default.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - governance-ga
      - host
    tty: true
  # ngrok-governance-ga:
  #   image: wernight/ngrok
  #   env_file:
  #     - environments/governance-ga/aca-py-agent.default.env
  #   command: ngrok http governance-ga-agent:3020 --log stdout
  #   networks:
  #     - governance-ga
  #     - host
  #   depends_on:
  #     - ledger-nodes
  #     - ledger-browser
  governance-ga-agent:
    image: ${ECR_REGISTRY}/governance-ga-agent:${IMAGE_TAG:-latest}
    container_name: governance-ga-agent
    build:
      context: .
      dockerfile: dockerfiles/agents/Dockerfile.agent
    env_file:
      - environments/governance-ga/aca-py-agent.default.env
    ports:
      - 0.0.0.0:3020:3020
      - 0.0.0.0:3021:3021
    depends_on:
      - governance-ga-wallets-db
      - ledger-nodes
      - ledger-browser
    networks:
      - governance-ga
      - host
    extra_hosts:
      - "host.docker.internal:host-gateway"
  governance-trust-registry:
    image: ${ECR_REGISTRY}/governance-trust-registry:${IMAGE_TAG:-latest}
    container_name: governance-trust-registry
    build:
      context: .
      dockerfile: ./dockerfiles/trustregistry/Dockerfile
    env_file:
      - environments/trustregistry/trustregistry.default.env
    ports:
      - 0.0.0.0:8001:8001
    volumes:
      - ./trustregistry:/trustregistry
    networks:
      - governance-ga
      - governance-multitenant
      - host
  governance-multitenant-web:
    image: ${ECR_REGISTRY}/governance-multitenant-web:${IMAGE_TAG:-latest}
    container_name: governance-multitenant-web
    build:
      context: .
      dockerfile: ./dockerfiles/fastapi/Dockerfile
    ports:
      - 0.0.0.0:8100:8000
    volumes:
      - ./shared_models/shared_models.py:/app/shared_models.py
      - ./app:/app
      - ./environments/governance-multitenant/fastapi.default.env:/app/.env
    depends_on:
      - governance-multitenant-wallets-db
      - ledger-nodes
      - ledger-browser
    networks:
      - governance-multitenant
      - host
    env_file:
      - environments/governance-multitenant/fastapi.default.env
  governance-webhooks-web:
    image: ${ECR_REGISTRY}/governance-webhooks-web
    container_name: governance-webhooks-web
    build:
      context: .
      dockerfile: ./dockerfiles/webhooks/Dockerfile
    ports:
      - 0.0.0.0:3010:3010
    volumes:
      - ./shared_models/shared_models.py:/webhooks/shared_models.py
      - ./webhooks:/webhooks
    networks:
      - governance-multitenant
      - governance-ga
      - host
    env_file:
      - environments/webhooks/fastapi.webhooks.env
    environment:
      - REDIS_URL=redis://wh-redis
  governance-endorser:
    build:
      context: .
      dockerfile: ./dockerfiles/endorser/Dockerfile
    volumes:
      - ./shared_models/shared_models.py:/shared_models.py
      - ./endorser:/endorser
    networks:
      - governance-multitenant
      - governance-ga
      - host
    env_file:
      - environments/endorser/endorser.env
  wh-redis:
    #image: ${ECR_REGISTRY}/redis:latest
    image: redis:latest
    container_name: wh-redis
    restart: always
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - $PWD/data:/data
    networks:
      - host
    env_file:
      - environments/webhooks/redis.env
  governance-multitenant-wallets-db:
    #image: ${ECR_REGISTRY}/postgres:11
    image: postgres:11
    container_name: governance-multitenant-wallets-db
    command: postgres -c listen_addresses='*'
    env_file:
      - environments/governance-multitenant/db.default.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - governance-multitenant
      - host
    tty: true
  ngrok-governance-multitenant:
    image: ${ECR_REGISTRY}/wernight/ngrok
    container_name: ngrok-governance-multitenant
    env_file:
      - environments/governance-multitenant/aca-py-agent.default.env
    command: ngrok http governance-multitenant-agent:3020 --log stdout
    networks:
      - governance-multitenant
      - host
    depends_on:
      - ledger-nodes
      - ledger-browser
  governance-multitenant-agent:
    image: ${ECR_REGISTRY}/governance-multitenant-agent
    container_name: governance-multitenant-agent
    build:
      context: .
      dockerfile: dockerfiles/agents/Dockerfile.author.agent
    env_file:
      - environments/governance-multitenant/aca-py-agent.default.env
    ports:
      - 0.0.0.0:4020:3020
      - 0.0.0.0:4021:3021
    depends_on:
      - governance-multitenant-wallets-db
      - ledger-nodes
      - ledger-browser
    networks:
      - governance-multitenant
      - governance-ga
      - host
  ledger-browser:
    image: ${ECR_REGISTRY}/ledger-browser
    container_name: ledger-browser
    build:
      context: https://github.com/didx-xyz/von-network.git
      dockerfile: Dockerfile
    command: "bash -c 'sleep 5; ./scripts/start_webserver.sh; sleep 60'"
    environment:
      - DOCKERHOST=${DOCKERHOST}
      - MAX_FETCH=50000
      - RESYNC_TIME=120
      - REGISTER_NEW_DIDS=True
      - LEDGER_INSTANCE_NAME=localhost
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger
    networks:
      - governance-multitenant
      - governance-ga
      - host
    depends_on:
      - ledger-nodes
  ledger-nodes:
    image: ${ECR_REGISTRY}/ledger-nodes
    container_name: ledger-nodes
    build:
      context: https://github.com/didx-xyz/von-network.git
      dockerfile: Dockerfile
    command: "bash -c 'sleep 15; ./scripts/start_nodes.sh; sleep 60'"
    ports:
      - 0.0.0.0:9701:9701
      - 0.0.0.0:9702:9702
      - 0.0.0.0:9703:9703
      - 0.0.0.0:9704:9704
      - 0.0.0.0:9705:9705
      - 0.0.0.0:9706:9706
      - 0.0.0.0:9707:9707
      - 0.0.0.0:9708:9708
    environment:
      - DOCKERHOST=${DOCKERHOST}
    volumes:
      - nodes-data:/home/indy/ledger
    networks:
      - governance-multitenant
      - governance-ga
      - host
  tails-server:
    image: ghcr.io/bcgov/tails-server:1.0.0
    container_name: tails-server
    ports:
      - 0.0.0.0:6543:6543
    networks:
      - governance-multitenant
      - governance-ga
      - host
    environment:
      - DOCKERHOST=${DOCKERHOST}
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path ./data
        --log-level INFO

volumes:
  webserver-cli:
  webserver-ledger:
  nodes-data:
  data:

networks:
  governance-multitenant:
  governance-ga:
  host:
