replicaCount: 1

daemon: false

strategy:
  type: Recreate

image:
  repository: "324190738845.dkr.ecr.af-south-1.amazonaws.com/governance-trust-registry"
  pullPolicy: Always
  tag: "baseline-04d67c5"

ingress:
  internal:
    enabled: true
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: trust-registry.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 8001

service:
  # if set, will run Pods on Node Network
  appProtocol: tcp
  hostNetwork: false
  port: 8001
  containerPort: 8001

httpProbes:
  {}
  # liveness:
  #   path: /
  # readiness:
  #   path: /
  # initialDelaySeconds: 2

persistence:
  enabled: true
  mountPath: /trustregistry-db
  capacity: 25Gi
  storageClassName: "gp3"

autoscaling:
  enabled: false

env:
  PYTHONPATH: /
  SQLALCHEMY_DATABASE_URL: sqlite:////trustregistry-db/trustregistry.db
  OPENAPI_NAME: Trustregistry
