replicaCount: 1

daemon: false

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m
  
image:
  repository: "324190738845.dkr.ecr.af-south-1.amazonaws.com/governance-webhooks-web"
  pullPolicy: Always
  tag: "baseline-04d67c5"

ingress:
  internal:
    enabled: true
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: webhooks.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 3010
  external:
    enabled: false

service:
  # if set, will run Pods on Node Network
  appProtocol: tcp
  hostNetwork: false
  port: 3010
  containerPort: 3010

httpProbes:
  {}
  # liveness:
  #   path: /
  # readiness:
  #   path: /
  # initialDelaySeconds: 2

persistence:
  enabled: false

configFiles:
  shared_models.py:
    path: /app/shared_models/shared_models.py
    content: |-
      {{ .Files.Get "assets/shared_models/shared_models.py" }}
  __init__.py:
    path: /app/shared_models/__init__.py
    content: |-
      {{ .Files.Get "assets/shared_models/__init__.py" }}

autoscaling:
  enabled: false

secretData:
  # REDIS_HOST: ""

extraSecretNamesForEnvFrom:
  - redis-host

env:
  ACAPY_WEBHOOK_PORT: 3010
  LOG_LEVEL: error
  OPENAPI_NAME: Webhooks
