args:
  - --wallet-type
  - askar
  - --auto-promote-author-did
  - --plugin
  - acapy_wallet_groups_plugin
  - --genesis-transactions-list
  - ./multi_ledger_config.yml

configFiles:
  multi_ledger_config.yml:
    path: /home/indy/multi_ledger_config.yml
    content: |-
      - id: default
        is_production: true
        is_write: true
        genesis_url: 'http://test.bcovrin.vonx.io/genesis'
      - id: bcovrinTest
        is_production: true
        genesis_url: 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis'

env:
  ACAPY_GENESIS_URL: ""
  ACAPY_AUTO_ENDORSE_TRANSACTIONS: false
