configFiles:
  multi_ledger_config.yml:
    path: /home/indy/multi_ledger_config.yml
    content: |-
      - id: default
        is_production: true
        is_write: true
        genesis_url: 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis'
      - id: bcovrinTest
        is_production: true
        genesis_url: 'http://test.bcovrin.vonx.io/genesis'

env:
  ACAPY_GENESIS_URL: ""
  ACAPY_MULTITENANT_ADMIN: false