secretData: null
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:402177810328:alias/helm/cloudapi-dev
          created_at: "2023-03-18T15:25:27Z"
          enc: AQICAHh+meefgfOs45hoVdYMdRjNJu8QOFZJCT24jUqx37Bl/gE7Qb0LKGYp3hWBZDZPR4SbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHIMwQMbMo0zOredbAgEQgDtwLZAYSPtIPbOeyVbyunQpjWq0d4mYUv4uCfuHB4qf+DIiN0XNdWTvP8Mx6mKGz/S+ipz+keNDqoqXLA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-18T15:25:27Z"
    mac: ENC[AES256_GCM,data:fMbz6DgI+rgpXBAshHQolKphwiNhKH962j0SJ/tEq4+tT6PUAaRttVEegIOd9xbumKyYvP+NYKROgsPyenyXBul+zoULZ5UsgwNctNqfvpGMllHEo2QS9I+DKPKG1t9b7qeOYpEmeMLh0GVfqJ+aLMcbDYS/+/YvbKFxDeEoF2k=,iv:3uIY3sJaL/0hZp6p8cQ0Ikiumg44qxahyuwPDMbLQEE=,tag:EDh7LbZ1UNRGOZdVuS1Nfw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
