secretData:
    ACAPY_LABEL: ENC[AES256_GCM,data:/P7A+HY48FanHLPIF90YcQ==,iv:XKJRyt/hXwaCpxVhawLCK0QKaGSaJX93pMDr1Tj4hQc=,tag:Z00iZ/vWnuGOpBtbbEV0dA==,type:str]
    ACAPY_WALLET_NAME: ENC[AES256_GCM,data:4mbCuipeifBzlY7EYkp7mw==,iv:2yd7DbZjuAd4TvLBywh1g6UgwieYjAjuyub1D6Sjtmw=,tag:hIBQUlv9zQdq14Wve5vf8g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:402177810328:alias/helm/cloudapi-dev
          created_at: "2023-03-18T15:25:27Z"
          enc: AQICAHh+meefgfOs45hoVdYMdRjNJu8QOFZJCT24jUqx37Bl/gFosqTD9bByZnJ31v370OUEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsRFIHDC01GVZrRBtAgEQgDtmu4WiBpYr4cbg4j1Ziq2ZLxT1LgvJfM9vhiXfX2TIBeHG5cXpz99pfIAA0b/MQjcZ3gzaPUFf+fvj6Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-18T15:25:27Z"
    mac: ENC[AES256_GCM,data:lGX1307XtbRVdE/elk/GB4TtaKfz/BJCtKFWJTbNZzYcJROq+fnHLaMSy03gb5aVqkHqRjoPZOjq8Vbfkc2VZS+43M+wESm2Z58sScMetwd68HQVfrWOstt+AVqUNrYhpwFvSMdhc/NwnuJ7PcQMGl5dl8+bsOPwpl4YJ1+xr3o=,iv:Flz5WTr/sbYQ4sNtVOn8vLltw2r7wqvdp23qOPgrCyQ=,tag:3nT071v6YDyl0cXMGNd5FA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
