secretData: null
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:402177810328:alias/helm/cloudapi-dev
          created_at: "2023-03-25T14:35:26Z"
          enc: AQICAHh+meefgfOs45hoVdYMdRjNJu8QOFZJCT24jUqx37Bl/gFLoV7hgU22QVi6gp57dOsoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMga52xnzAMDb99/LEAgEQgDuRBM+Ys8LI8hM2AvbDk5u2vOolkFjyyWIXNMx01uyMqVM7zPDIAYO4foqDtvSOx+1h+0KPu03TeZ5hRw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-25T14:35:58Z"
    mac: ENC[AES256_GCM,data:/Nj6McnTR77Rz49AzueQtbahX5WrK2R8N78oYzsJqkVp3qidJP9imJgEBBs9u4xvUkBxQTVNcQwBFJ4GTWW9n1xUkVwxFrV9lrsCLm3ymf1fNtcl2WedIB8ImCF3umuMUfIZ27mLIG4nTUQ/090y/WM5Uv7/InPtXfT30F73b9Y=,iv:khCvijK1uD3JXYsC6umehi3ZJ+QNF7ng2LkXuHNB+F4=,tag:SJM7IxbUYdVUx7m3+evzlg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
